import streamlit as st

# --- 1. CONFIGURACIÓN DE LA PÁGINA ---
st.set_page_config(
    page_title="Buscador Steal a Brainrot", 
    page_icon="🔍", 
    layout="centered"
)

st.title("🔍 Base de Datos Oficial - Steal a Brainrot")
st.write("Busca información exacta sobre rarezas, utilidades y bases que pintan.")

PERSONAJES = {
    "nobini pizzanini": {"rareza": "Comun", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "lirili larila": {"rareza": "Comun", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tim cheese": {"rareza": "Comun", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "fluriflura": {"rareza": "Comun", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "talpa di fero": {"rareza": "Comun", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "svinina bombardino": {"rareza": "Comun", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "nobini santini": {"rareza": "Comun", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "raccooni jandelini": {"rareza": "Comun", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "pipi kiwi": {"rareza": "Comun", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tartaragno": {"rareza": "Comun", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "holy arepa": {"rareza": "Comun", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "pipi corni": {"rareza": "Comun", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "trippi troppi": {"rareza": "Raro", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "gangster footera": {"rareza": "Raro", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bandito bobritto": {"rareza": "Raro", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "boneca ambalabu": {"rareza": "Raro", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "cacto hipopotamo": {"rareza": "Raro", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "ta ta ta ta sahur": {"rareza": "Raro", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "cupcake koala": {"rareza": "Raro", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tric trac barabom": {"rareza": "Raro", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "frogo elfo": {"rareza": "Raro", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "pipi avocado": {"rareza": "Raro", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "pengolino nuvoletto": {"rareza": "Raro", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "pinealotto fruttarino": {"rareza": "Raro", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "cappuccino assassino": {"rareza": "Epico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "brr brr patapim": {"rareza": "Epico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "avocadini antilopini": {"rareza": "Epico", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "trulimero trulicina": {"rareza": "Epico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bambini crostini": {"rareza": "Epico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "malame amarele": {"rareza": "Epico", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bananita dolphinita": {"rareza": "Epico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "perochello lemonchello": {"rareza": "Epico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "brri brri bicus dicus bombicus": {"rareza": "Epico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "avocadini guffo": {"rareza": "Epico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "ti ti ti sahur": {"rareza": "Epico", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "mangolini parrochini": {"rareza": "Epico", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "frogato pirato": {"rareza": "Epico", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "gato celesto": {"rareza": "Epico", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "salamino penguino": {"rareza": "Epico", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "doi doi doi": {"rareza": "Epico", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "penguin tree": {"rareza": "Epico", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "wombo rollo": {"rareza": "Epico", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "penguino cocosino": {"rareza": "Epico", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "mummio rappitto": {"rareza": "Epico", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "burbaloni loliloli": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "chimpanzini bananini": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "ballerina capuccina": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "chef crabracadabra": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "lionel cactuseli": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "glorbo fruttodrillo": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "quivioli ameleonni": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bluberrini octopusini": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "clickerino crabo": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "caramello filtrello": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "pipi potato": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "strawberrelli flamingelli": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "cocosini mama": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bandito axolito": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "pandaccini bananini": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "quackula": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "pi pi watermelon": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "buho del cielo": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "sigma boy": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "chocco bunny": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "puffaball": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "sigma girl": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "sealo regalo": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "electro quacko": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Cyber"},
    "buho de fuego": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "seraphino gruyero": {"rareza": "Legendario", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "frigo camelo": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "orangutini ananassini": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "rhino toasterino": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bombardiro crocodilo": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "brutto gialutto": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "spioniro golubiro": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bombombini gusini": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "zibra zubra zibralini": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tigrilini watermelini": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "avocadorilla": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "cavallo virtuoso": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "gorillo subwoofero": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "gorillo watermelondrillo": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "stoppo luminino": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tob tobi tobi": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "lerulerulerule": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "ganganzelli trulala": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "te te te sahur": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "rhino helicopterino": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "magi ribbitini": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tracoducotulu delapeladustuz": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "jingle jingle sahur": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "los noobinis": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "cachorrito melonito": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "spongini quackini": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "carloo": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bee loco": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Cyber"},
    "harpuccino": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "carrotini brainini": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "cocoteddy": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Cyber"},
    "centrucci nuclucci": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "toiletto focaccino": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "jacko spaventosa": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bananito bandito": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tree tree tree sahur": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "fizzy soda": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "berenjello angello": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "bucketoro": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Cyber"},
    "orbi mochi": {"rareza": "Mitico", "utilidades": "", "base_pinta": "Cyber"},
    "cocofanto elefanto": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "girafa celestre": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "gattatino nyanino": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "chihuanini taconini": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "matteo": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tralalero tralala": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los crocodillitos": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tigroligre frutonni": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "money money man": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "espresso signora": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "unclito samito": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "odin din din dun": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tipi topi taco": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "alessio": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tralalita tralala": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "orcalero orcala": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tukanno bananno": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "extinct ballerina": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "vampira cappucina": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "jacko jack jack": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "urubini flamenguini": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "trenostuzzo turbo 3000": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "capi taco": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los chihuaninis": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "divino platypio": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "gattito tacoto": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "trippi troppi troppa trippa": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "sundrilla sundae": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Cyber"},
    "las capuchinas": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "ballerino lololo": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "pineaplino": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "bulbito bandito traktorito": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los tungtungtungcitos": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "pakrahmatmamat": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "ballerina peppermintina": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "los bombinitos": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bombardini tortini": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "pakrahmatmatina": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "brr es teh patipum": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "piccione macchina": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tractoro dinosauro": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los orcalitos": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "grabbo limonetta": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "orcalita orcala": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "cacasito satalito": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "aquanaut": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "squalanana": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "corn corn corn sahur": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tartaruga cisterna": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "mummy ambalabu": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "snailenzo": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "lazy ducky": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "trenotubo axolotrico 9000": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Cyber"},
    "yeti claus": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "ginger globo": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "tootini shrimpini": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "los tipi tacos": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "granchiello spiritello": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "frio ninja": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "lumaca malefica": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Cyber"},
    "buho de noelo": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "boba panda": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "bunny tralala": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "piccionetta macchina": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bambu bambu sahur": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los gattitos": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "mastodontico telepiedone": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "christmasmamat": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "anpali babel": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "limonita splashita": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Cyber"},
    "noo la polizia": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "astrolero cervalero": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "cappuccino clownino": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "brasilini berimbini": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "luv luv luv": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "patteo": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "krupuk pagi pagi": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "skull skull skull": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "belula beluga": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "cocoa assassino": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "tentacolo tecnico": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "ginger cisterna": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "pandanini frostini": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "dolphini jetskini": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "pop pop sahur": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "karkerheart luvkur": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "appelini": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "clovkur kurkur": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "eggdin egg egg dun": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "dumborino miracello": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "flippo marino": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Cyber"},
    "robo grafito": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Cyber"},
    "tortuginni sandcastlini": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Cyber"},
    "pretzo robo": {"rareza": "Brainrot God", "utilidades": "", "base_pinta": "Cyber"},
    "jackorilla": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "sammyni spyderini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "la vacca saturno saturnita": {"rareza": "Secret", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "karkerkar kurkur": {"rareza": "Secret", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los matteos": {"rareza": "Secret", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bisonte giuppitere": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "trenostruzzo turbo 4000": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tortuginni dragonfrutini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "dul dul dul": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "blackhole goat": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "chachechi": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "agarrini la palini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los spyderinis": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "extinct tralalero": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "la cucaracha": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los tortus": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los tralaleritos": {"rareza": "Secret", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "zombie tralala": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "vulturino skeletono": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "boatito auratito": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "guerriro digitale": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "yess my examine": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "la vacca prese presente": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "la karkerkar combinasion": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "reindeer tralala": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "extinct mateo": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "las tralaleritas": {"rareza": "Secret", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "pumpkini spyderini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "rocco disco": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "frankentteo": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los trios": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "job job job sahur": {"rareza": "Secret", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "karker sahur": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "las vaquitas saturnitas": {"rareza": "Secret", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los karkeritos": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "santteo": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "fishboard": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "la vacca jacko linterino": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "buntteo": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "triplito tralaleritos": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "trickolino": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "paradiso axolottino": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "goat": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "giftini spyderini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "perrito burrito": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "graipuss medussi": {"rareza": "Secret", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "love love love sahur": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "bombardiro vaccariro": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "la vacca lepre leprino": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "1x1x1x1": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los cucarachas": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "easter easter easter sahur": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "craburger": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "please my present": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "cuadramat and pakrahmatmamat": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "los jobcitos": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bunnyman": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "berryno": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "nooo my hotspot": {"rareza": "Secret", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "noo my examine": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "telemorte": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "la sahur combinasion": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "list list list sahur": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "to to to sahur": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bunny bunny bunny sahur": {"rareza": "Secret", "utilidades": "", "base_pinta": ""},
    "glaciator": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "pirulitoita bicicleteira": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "pot hotspot": {"rareza": "Secret", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "25": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "santa hotspot": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "buho de volto": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "horegini boom": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "rocketini frostini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "pot pumpkin": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "naughty naughty": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "quesadilla crocodila": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bunito bunito spinito": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "cupid cupid sahur": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "ho ho ho sahur": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "mi gatito": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "octoball": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "cupid hotspot": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "quesadillo vampiro": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "brunito marsito": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "eid eid eid sahur": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "chicleteira bicicleteira": {"rareza": "Secret", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "luck luck luck sahur": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "flancito": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "burrito bandito": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "chicleterina bichicleterina": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "granny": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "chill puppy": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "los bunitos": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "futbolini skatini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "los quesadillas": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "noo my candy": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "arcadopus": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "los nooo my hotspotsitos": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "serafinna medusella": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "noo my present": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "rang ring bus": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "flipa sandala": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "los mi gatitos": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "obrello topolino": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "strawberrita": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "los chicleteiras": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "noo my eggs": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "john doe": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "67": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "donkeyturbo express": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "sushi inu": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "los burritos": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "los 25": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "la grande combinasion": {"rareza": "Secret", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tacodrillo crocodillo": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "mariachi corazoni": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "noo my heart": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "swag soda": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "noo my gold": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "chimnino": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "nuclearo dinossauro": {"rareza": "Secret", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bananito": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "chicleteira noelteira": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "los combinasionas": {"rareza": "Secret", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "baskito": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "tacorita bicicleta": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los sweethearts": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "camera ramena": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "spinny hammy": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "dj panda": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "chicleteira cupideira": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "las sis": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "girafini raftini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "snailo clovero": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "los planitos": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "los jolly combinasionas": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "cigno fulgoro": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "los hotspotsitos": {"rareza": "Secret", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "frullato flamingo": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "las spooky combinasionas": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "churrito bunnito": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "money money puggy": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los mobilis": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "capitano gullini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "celularcini viciosini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los 67": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los candies": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "los fruits": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "la extinct grande": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los bros": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bacuro and egguru": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "la spooky grande": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "money money reindeer": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "chillin chili": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "chipso and queso": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tuff toucan": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "mieteteira bicicleteira": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tralalendon": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "globa steppa": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "goblino uniciclino": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "esok sekolah": {"rareza": "Secret", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "la jolly grande": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "los puggies": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "sand sand sand": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "los cupids": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "w or l": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "los mariachis": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "los primos": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "eviledon": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "los tacoritas": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "fragola la la la": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "lovin rose": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "abyssaloco": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "coco and mango": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "tang tang keletang": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "ketupat kepat": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "dug dug dug": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "la taco combinasion": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "tictac sahur": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "la romantic grande": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "swaggy bros": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioctive, Cursed, Divine, Cyber"},
    "la lucky grande": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "orcaledon": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "tirilikalika tirilikalako": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "gym bros": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "rico dinero": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "ketchuro and musturo": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "lavadorito spinito": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "jolly jolly sahur": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "gold gold gold": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "money money bros": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "fishino clownino": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "la anniversary grande": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "nacho spyder": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "rosetti tualetti": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "garama and madundung": {"rareza": "Secret", "utilidades": "", "base_pinta": "Candy, Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "hopilikalika hopilikalako": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "caylusaurus": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "stakini fattini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "la easter grande": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "spaghetti tualetti ": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "cloverat clapat": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "quackini snackini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "ventoliero pavonero": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "guest 666": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "festive 67": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "sammyni fattini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "rubrikiko": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "los spaghettis": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "bearito cabinito": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "la ginger sekolah": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "los hackers": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "los chillis": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "ginger gerat": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "sooky and pumpky": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "boppin bunny": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "sammyni cakini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "la food combinasion": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "duggy bros": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "la casa boo": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "fragrama and chocrama": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "cash or card": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "los sekolahs": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "foxini lanternini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "kalika bros": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "antonio": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "la secret combinasion": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "pancake and syrup": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "fortunu and cashuru": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "los amigos": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "reinito sleighito": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "ketupat bros": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "arcadragon": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "burguro and fryuro": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "cooki and milki": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "capitano moby": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "rosey and teddy": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "bunny and eggy": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "popcuru and fizzuru": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "jelly moby": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "celestial pegasus": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "cerberus": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "venuspino": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "elefanto frigo": {"rareza": "Secret", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "hydra bunny": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "kraken": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "digi narwhal": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "la supreme combinasion": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "love love bear": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "dragon cannelloni": {"rareza": "Secret", "utilidades": "", "base_pinta": "Lava, Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "signore carapace": {"rareza": "Secret", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "hydra dragon cannelloni": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cursed, Divine, Cyber"},
    "dragon gingerini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "dragon aquanini": {"rareza": "Secret", "utilidades": "", "base_pinta": "Cyber"},
    "griffin": {"rareza": "Secret", "utilidades": "", "base_pinta": "Divine, Cyber"},
    "skibidi toilet": {"rareza": "OG", "utilidades": "", "base_pinta": "Radioactive, Cursed, Divine, Cyber"},
    "john pork": {"rareza": "OG", "utilidades": "", "base_pinta": "Cyber"},
    "meowl": {"rareza": "OG", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "headless horseman": {"rareza": "OG", "utilidades": "", "base_pinta": "Ying Yang, Radioactive, Cursed, Divine, Cyber"},
    "strawberry elephant": {"rareza": "OG", "utilidades": "", "base_pinta": "Galaxy, Ying Yang, Radioactive, Cursed, Divine, Cyber"},
}
# --- 3. PROCESAMIENTO Y CONTEOS (MÓDULO DE CÁLCULO) ---
total_personajes = len(PERSONAJES)

# Contar cuántos personajes hay por tipo de rareza
conteos_rareza = {}
for p_datos in PERSONAJES.values():
    r = p_datos["rareza"]
    conteos_rareza[r] = conteos_rareza.get(r, 0) + 1

# --- 4. PANEL DE ESTADÍSTICAS (MÉTRICAS DINÁMICAS) ---
st.markdown("### 📊 Tablero de Conteos Generales")
m1, m2, m3 = st.columns(3)
m1.metric(label="Total Personajes Registrados", value=total_personajes)
m2.metric(label="Total Categorías de Rareza", value=len(conteos_rareza))
m3.metric(label="Personajes de Rareza Máxima (Secret)", value=conteos_rareza.get("Secret", 0))

# Muestra un pequeño desglose rápido de conteos en un expander acoplado
with st.expander("🔢 Ver total exacto por cada Rareza"):
    columnas_rar = st.columns(4)
    rarezas_lista = ["Comun", "Raro", "Epico", "Legendario", "Mitico", "Brainrot God", "Secret", "OG"]
    for idx, r_name in enumerate(rarezas_lista):
        with columnas_rar[idx % 4]:
            st.markdown(f"**{r_name}:** `{conteos_rareza.get(r_name, 0)}`")

# --- 5. INTERFAZ GRÁFICA DE BÚSQUEDA ---
st.write("---")
st.markdown("### 🔍 Panel de Búsqueda Avanzada")
consulta = st.text_input(
    "Escribe el nombre completo de un personaje o una base que pinta (Ej. 'Candy', 'Lava', 'Sigma Boy'):", 
    placeholder="Escribe aquí tu consulta..."
).strip().lower()

col1, col2 = st.columns(2)

with col1:
    if st.button("Buscar por Personaje Exacto", use_container_width=True):
        if consulta:
            if consulta in PERSONAJES:
                p = PERSONAJES[consulta]
                st.success(f"🎯 ¡Encontrado! Datos de: **{consulta.title()}**")
                st.write(f"**Rareza:** {p['rareza']}")
                st.write(f"**Utilidades:** {p['utilidades'] if p['utilidades'] else '*(En blanco)*'}")
                st.write(f"**Base que pinta:** {p['base_pinta'] if p['base_pinta'] else '*(Ninguna - En blanco)*'}")
            else:
                st.error("❌ El personaje no se encuentra registrado en la base de datos.")
        else:
            st.info("Por favor, escribe el nombre de un personaje.")

with col2:
    if st.button("Buscar por Base que Pinta", use_container_width=True):
        if consulta:
            encontrados = []
            for nombre, datos in PERSONAJES.items():
                if consulta in datos["base_pinta"].lower():
                    encontrados.append((nombre.title(), datos["rareza"]))
            
            if encontrados:
                # El sistema cuenta y reporta el número exacto del filtro
                st.success(f"✨ Conteo: **{len(encontrados)}** personajes pintan base **'{consulta.title()}'**:")
                for nom, rar in encontrados:
                    st.write(f"• **{nom}** — *({rar})*")
            else:
                st.error(f"❌ Ningún personaje tiene asignada la base '{consulta.title()}'.")
        else:
            st.info("Por favor, introduce un tipo de pintura (Ej: Candy, Lava, Galaxy).")

# --- 6. VISUALIZACIÓN COMPLETA POR CATEGORÍAS ---
st.write("---")
with st.expander("📂 Inspeccionar toda la Base de Datos (Filtro por Categoría)"):
    rareza_seleccionada = st.selectbox(
        "Selecciona una categoría para desplegar la lista:",
        ["Comun", "Raro", "Epico", "Legendario", "Mitico", "Brainrot God", "Secret", "OG"]
    )
    
    # Muestra dinámicamente cuántos hay en la sección elegida justo en el encabezado
    st.write(f"### Personajes en categoría **{rareza_seleccionada}** (Total: {conteos_rareza.get(rareza_seleccionada, 0)})")
    
    for nombre, datos in PERSONAJES.items():
        if datos["rareza"] == rareza_seleccionada:
            base = f" | **Pinta:** {datos['base_pinta']}" if datos['base_pinta'] else " | **Pinta:** N/A"
            util = f" | **Utilidad:** {datos['utilidades']}" if datos['utilidades'] else ""
            st.write(f"• **{nombre.title()}**{base}{util}")
